// End-to-end integration test for the TLS transport substrate.
//
// The plain-`ws://` coverage in `wss_integration.rs` exercises the auth
// handshake, dispatch loop, subscribe / broadcast, and CRUD ops. This
// file is scoped to what plain-TCP tests cannot prove:
//
//   * `TlsMaterial::to_server_config` produces a rustls ServerConfig
//     that survives a real TLS handshake (not just a build).
//   * `run_with_tls_from_listener` wires axum-server + rustls correctly
//     over an already-bound listener.
//   * A `wss://` client that trusts the generated cert can complete
//     the WebSocket upgrade and the auth handshake end-to-end.
//
// One test is enough here — every non-TLS behaviour is covered in the
// plain-TCP file. This file exists to guard the TLS wiring against
// silent regressions (cert loading, rustls config wiring, bind path).

use agent_terminal_lib::auth_stub::AuthStub;
use agent_terminal_lib::ModEngineHandle;
use agent_terminal_lib::projects_cache::ProjectsCache;
use agent_terminal_lib::protocol::{ClientFrame, ServerFrame};
use agent_terminal_lib::pty_manager::PtyMap;
use agent_terminal_lib::stream_hub::StreamHub;
use agent_terminal_lib::tls::TlsMaterial;
use agent_terminal_lib::wss_server::{self, ServerState};

use futures_util::{SinkExt, StreamExt};
use rustls_pemfile::certs as parse_certs;
use std::collections::HashMap;
use std::net::SocketAddr;
use std::sync::{Arc, Mutex};
use std::time::Duration;
use tokio_rustls::rustls::pki_types::CertificateDer;
use tokio_rustls::rustls::{ClientConfig, RootCertStore};
use tokio_tungstenite::tungstenite::Message;
use tokio_tungstenite::Connector;

/// Build a fully-wired ServerState + TLS material, spawn the server on
/// an ephemeral port, and hand back the addr plus the cert PEM so the
/// caller can build a rustls client that trusts it. Waits until the
/// listener is actually accepting before returning — deterministic on
/// slow CI, fast on a healthy dev box.
async fn spawn_tls_server(
    token: &str,
) -> (SocketAddr, String) {
    // Bind the listener ourselves so the OS picks a free port; hand the
    // bound listener to run_with_tls_from_listener. Blocking mode is
    // fine — axum-server converts to non-blocking internally.
    let listener = std::net::TcpListener::bind("127.0.0.1:0").expect("bind");
    let addr = listener.local_addr().expect("local_addr");

    // TLS material persisted to a tempdir; drop it after we've extracted
    // the in-memory PEMs since the ServerConfig doesn't touch the files
    // again.
    let tmp = tempfile::tempdir().expect("mkdtemp");
    let material = TlsMaterial::load_or_generate(
        tmp.path(),
        vec!["localhost".into(), "127.0.0.1".into()],
    )
    .expect("tls material");
    let cert_pem = material.cert_pem.clone();
    let server_config = material.to_server_config().expect("server config");
    let rustls_config = Arc::new(
        axum_server::tls_rustls::RustlsConfig::from_config(Arc::new(server_config)),
    );

    let auth = Arc::new(AuthStub::new_for_tests(
        token.to_string(),
        "test-device".into(),
        addr,
    ));

    let hub = StreamHub::new(None);
    let pty_map: PtyMap = Arc::new(Mutex::new(HashMap::new()));
    let projects_cache = Arc::new(ProjectsCache::new());
    let state = Arc::new(ServerState {
        hub: Arc::clone(&hub),
        auth,
        projects_cache,
        pty_map,
        mod_engine_handle: ModEngineHandle::noop(),
        cwd_table: Arc::new(Mutex::new(HashMap::new())),
        app_handle: None,
        mobile_op_inboxes: Arc::new(wss_server::MobileOpInboxes::new()),
    });

    tokio::spawn(async move {
        let _ = wss_server::run_with_tls_from_listener(listener, state, rustls_config).await;
    });

    // Poll TCP-level readiness — accepting the connect proves the
    // axum-server accept loop is live. TLS handshake happens after
    // TCP accept, so this is enough to avoid the "server not up yet"
    // race in the test client below.
    let deadline = std::time::Instant::now() + Duration::from_secs(5);
    loop {
        if tokio::net::TcpStream::connect(addr).await.is_ok() {
            break;
        }
        if std::time::Instant::now() >= deadline {
            panic!("tls wss server never came up at {addr}");
        }
        tokio::time::sleep(Duration::from_millis(5)).await;
    }
    (addr, cert_pem)
}

/// Build a rustls-backed Connector for tokio-tungstenite that trusts
/// exactly the cert generated by the test's server. Installs `ring` as
/// the process-wide crypto provider (idempotent — a second call from
/// the server side is a no-op).
fn build_client_connector(cert_pem: &str) -> Connector {
    let _ = tokio_rustls::rustls::crypto::ring::default_provider().install_default();

    let mut roots = RootCertStore::empty();
    let mut reader = cert_pem.as_bytes();
    for cert in parse_certs(&mut reader) {
        let cert: CertificateDer<'static> = cert.expect("parse cert");
        roots.add(cert).expect("add root");
    }

    let config = ClientConfig::builder()
        .with_root_certificates(roots)
        .with_no_client_auth();

    Connector::Rustls(Arc::new(config))
}

#[tokio::test]
async fn wss_handshake_and_auth_ok_over_tls() {
    let (addr, cert_pem) = spawn_tls_server("known-token").await;
    // Cert SANs are `localhost` + `127.0.0.1`; connect via `localhost`
    // so hostname verification checks a name SAN rather than an IP SAN.
    // Both work; localhost is closer to the shape of the real mobile
    // client's URL.
    let url = format!("wss://localhost:{}/stream", addr.port());
    let connector = build_client_connector(&cert_pem);

    let (mut ws, _) = tokio_tungstenite::connect_async_tls_with_config(
        url,
        None,
        false,
        Some(connector),
    )
    .await
    .expect("wss handshake");

    let auth = ClientFrame::Auth { token: "known-token".into() };
    let json = serde_json::to_string(&auth).expect("serialise");
    ws.send(Message::Text(json.into())).await.expect("send auth");

    // Expect AuthOk first.
    let msg = tokio::time::timeout(Duration::from_secs(5), ws.next())
        .await
        .expect("timed out waiting for auth_ok")
        .expect("stream closed unexpectedly")
        .expect("ws error");
    let text = match msg {
        Message::Text(t) => t.to_string(),
        other => panic!("expected text frame, got {other:?}"),
    };
    let frame: ServerFrame = serde_json::from_str(&text).expect("parse ServerFrame");
    match frame {
        ServerFrame::AuthOk { device_name } => {
            assert_eq!(device_name, "test-device");
        }
        other => panic!("expected AuthOk, got {other:?}"),
    }

    // The server pushes Projects right after AuthOk. Consume + assert
    // it shows up over TLS to prove the whole post-handshake outbox
    // path (not just the auth reply) survives the encrypted transport.
    let msg = tokio::time::timeout(Duration::from_secs(5), ws.next())
        .await
        .expect("timed out waiting for projects")
        .expect("stream closed unexpectedly")
        .expect("ws error");
    let text = match msg {
        Message::Text(t) => t.to_string(),
        other => panic!("expected text frame, got {other:?}"),
    };
    let frame: ServerFrame = serde_json::from_str(&text).expect("parse ServerFrame");
    assert!(
        matches!(frame, ServerFrame::Projects { .. }),
        "expected Projects push after AuthOk, got {frame:?}"
    );
}
