/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectIdRouteImport } from './routes/$projectId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIdIndexRouteImport } from './routes/$projectId/index'
import { Route as ProjectIdTabIdRouteImport } from './routes/$projectId/$tabId'

const ProjectIdRoute = ProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIdIndexRoute = ProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectIdRoute,
} as any)
const ProjectIdTabIdRoute = ProjectIdTabIdRouteImport.update({
  id: '/$tabId',
  path: '/$tabId',
  getParentRoute: () => ProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteWithChildren
  '/$projectId/$tabId': typeof ProjectIdTabIdRoute
  '/$projectId/': typeof ProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$projectId/$tabId': typeof ProjectIdTabIdRoute
  '/$projectId': typeof ProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectId': typeof ProjectIdRouteWithChildren
  '/$projectId/$tabId': typeof ProjectIdTabIdRoute
  '/$projectId/': typeof ProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$projectId' | '/$projectId/$tabId' | '/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$projectId/$tabId' | '/$projectId'
  id: '__root__' | '/' | '/$projectId' | '/$projectId/$tabId' | '/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdRoute: typeof ProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$projectId': {
      id: '/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof ProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectId/': {
      id: '/$projectId/'
      path: '/'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof ProjectIdIndexRouteImport
      parentRoute: typeof ProjectIdRoute
    }
    '/$projectId/$tabId': {
      id: '/$projectId/$tabId'
      path: '/$tabId'
      fullPath: '/$projectId/$tabId'
      preLoaderRoute: typeof ProjectIdTabIdRouteImport
      parentRoute: typeof ProjectIdRoute
    }
  }
}

interface ProjectIdRouteChildren {
  ProjectIdTabIdRoute: typeof ProjectIdTabIdRoute
  ProjectIdIndexRoute: typeof ProjectIdIndexRoute
}

const ProjectIdRouteChildren: ProjectIdRouteChildren = {
  ProjectIdTabIdRoute: ProjectIdTabIdRoute,
  ProjectIdIndexRoute: ProjectIdIndexRoute,
}

const ProjectIdRouteWithChildren = ProjectIdRoute._addFileChildren(
  ProjectIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdRoute: ProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
